### ISSUE TITLE
Get sources from the original source

### ISSUE THREAD

**Issue by opi** [kemenaran/yunohost-mattermost#1]
First, thanks for packagging mattermost, it's awesome !

I got one concern about the way you add app sources during installation ( https://github.com/kemenaran/yunohost-mattermost/blob/master/scripts%2Finstall#L64-L68 )
Adding a [executable binary file](https://github.com/kemenaran/yunohost-mattermost/blob/master/sources%2Fbin%2Fplatform) in your repository is not really recommended; I'd rather download original source from Github as mentionned in the [upstream documentation](https://github.com/mattermost/platform/blob/release-1.0.0/doc/install/prod-ubuntu.md#setup-mattermost-server)

I could provide a patch in the next few days if you don't have time to do that.

thx again

**Comment by kemenaran** [comment]
Thanks for the feedback @opi!

Sure, I can do that. I had a feeling that Yunohost apps had a tendency to include the app sources inside the app package; but maybe it's not that reasonable when it includes binaries, indeed.

_(For the record, I initially misread your comment, and thought you wanted to compile the binaries from source on the machine. I have long notes to explain this, but out they go :)_

**Comment by opi** [comment]
You're right about that tendency, it's an old one, and we try to move away from that ! You know, security is a process ... ;)

**Comment by kemenaran** [comment]
This should be fixed ; binary release is now downloaded at install-time.

**Comment by opi** [comment]
Oh great !!

As your app is still in development and without a huge user base, I wonder if it's not a good time to get rid of some git history to avoid downloading a huge repo during git clone while installing.

Maybe it's not a good idea, but playing with `git rebase` could help us remove the commit that add mattermost source.

**Comment by kemenaran** [comment]
Good idea ; I've just done that, using `git-filter-branch` to remove the `sources` directory from the git history.

The repo size is now 12 Ko ; not bad :)

**Comment by opi** [comment]
So good, thanks for your work !
